name: todoms
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  flutter_riverpod: ^2.1.1
  intl: ^0.17.0
  table_calendar: ^3.0.8
  vibration: ^1.7.6
  shared_preferences: ^2.0.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  supercharged: ^2.1.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true